apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener

metadata:
  name: teste-cicd-listener

spec:

  triggers:

    - name: teste-cicd-trigger

      bindings:

        - ref: teste-cicd-binding

      template:

        ref: teste-cicd-template