apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  name: teste-pipeline-run

  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"

spec:
  pipelineRef:
    name: teste-pipeline

  params:
    - name: repo-url
      value: "{{repo_url}}"

    - name: revision
      value: "{{revision}}"

    - name: image
      value: "ghcr.io/minha-organizacao/teste:latest"

  workspaces:
    - name: source
      emptyDir: {}