apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate

metadata:
  name: teste-cicd-template

spec:

  params:

    - name: git-url

    - name: git-revision

    - name: image

  resourcetemplates:

    - apiVersion: tekton.dev/v1
      kind: PipelineRun

      metadata:
        generateName: teste-cicd-

      spec:

        pipelineRef:
          name: teste-cicd

        params:

          - name: git-url
            value: $(tt.params.git-url)

          - name: git-revision
            value: $(tt.params.git-revision)

          - name: image
            value: $(tt.params.image)

        workspaces:

          - name: source
            emptyDir: {}